base:
  project: winequality-project
  random_state: 42
  target_col: Class

data_source:
  local_source: data_given/PDFMalware2022.csv

load_data:
  raw_dataset_csv: data/raw/PDFMalware2022.csv

preprocess_data:
  preprocessed_dataset_path: data/processed/preprocesssed_PDFMalware2022.csv

feature_selection:
  preprocessed_dataset_path: data/processed/PDFMalware2022_final.csv

split_data:
  train_path: data/processed/train_PDFMalware2022.csv
  test_path: data/processed/test_PDFMalware2022.csv
  test_size: 0.3

estimators:
  RandomForestClassifier:
    params:
      alpha: 0.9
      l1_ratio: 0.4
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib