base:
  project: malware-prediction-project
  random_state: 42
  target_col: Class

data_source:
  local_source: data_given/PDFMalware2022.csv

load_data:
  raw_dataset_csv: data/raw/PDFMalware2022.csv

preprocess_data:
  preprocessed_dataset_path: data/processed/preprocesssed_PDFMalware2022.csv

feature_selection:
  preprocessed_dataset_path: data/processed/PDFMalware2022_final.csv

split_data:
  train_path: data/processed/train_PDFMalware2022.csv
  test_path: data/processed/test_PDFMalware2022.csv
  test_size: 0.3

estimators:
  RandomForestClassifier:
    params:
      n_estimators: 50
      min_samples_split: 4
      min_samples_leaf: 5
      max_features: 'auto'
      max_depth: 94
      criterion: 'gini'
#      n_estimators: 100
#      min_samples_split: 8
#      min_samples_leaf: 6
#      max_features: 'auto'
#      max_depth: 50
#      criterion: 'gini'

model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: RandomForest Classifier
  run_name: mlops
  registered_model_name: RFForestMalwarePrediction
  remote_server_uri: http://0.0.0.0:80
